# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Login(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, password: str=None, user_name: str=None):  # noqa: E501
        """Login - a model defined in Swagger

        :param password: The password of this Login.  # noqa: E501
        :type password: str
        :param user_name: The user_name of this Login.  # noqa: E501
        :type user_name: str
        """
        self.swagger_types = {
            'password': str,
            'user_name': str
        }

        self.attribute_map = {
            'password': 'password',
            'user_name': 'userName'
        }
        self._password = password
        self._user_name = user_name

    @classmethod
    def from_dict(cls, dikt) -> 'Login':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Login of this Login.  # noqa: E501
        :rtype: Login
        """
        return util.deserialize_model(dikt, cls)

    @property
    def password(self) -> str:
        """Gets the password of this Login.


        :return: The password of this Login.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this Login.


        :param password: The password of this Login.
        :type password: str
        """

        self._password = password

    @property
    def user_name(self) -> str:
        """Gets the user_name of this Login.


        :return: The user_name of this Login.
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name: str):
        """Sets the user_name of this Login.


        :param user_name: The user_name of this Login.
        :type user_name: str
        """

        self._user_name = user_name
